"""
Django settings for HostManagement project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# 加载.env
import os
from dotenv import load_dotenv
load_dotenv()  # 加载.env文件的变量

from pathlib import Path

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-$9ui80c75&6f1wl(lsjzlmiej*qaww5@@xb_@u#q#m3xjrzlmz'
)

from cryptography.fernet import Fernet
# 1. 生成Fernet密钥（执行下方命令，复制结果粘贴到此处）
# 生成命令：python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
FERNET_PWD_KEY = os.environ.get('FERNET_PWD_KEY')  # 示例：gAAAAABlxxxxxxx（一串无规律字符串）
# 2. 初始化Fernet加密实例，供模型调用
FERNET_PWD_CRYPT = Fernet(FERNET_PWD_KEY)



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'host',
    'city',
    'server_room',
    'statistic',
    # Celery扩展
    'django_celery_results',
    'django_celery_beat',
]

MIDDLEWARE = [
    'HostManagement.middleware.PerformanceMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HostManagement.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HostManagement.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# 日志系统配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # 关键：不关闭任何原有日志器
    # 日志处理器（输出到控制台+文件）
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'default'},
        # 审计日志文件（每天切割，保留30天）
        'pwd_audit_file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': 'logs/host_pwd_audit.log',  # 日志文件路径
            'formatter': 'pwd_audit',
            'when': 'midnight',  # 每天凌晨切割日志
            'backupCount': 30,   # 保留30天日志
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',  # 核心修改：把根日志器级别降到INFO，让INFO及以上日志都输出
    },
    # 日志格式（审计日志单独格式，便于查看）
    'formatters': {
        'default': {'format': '%(asctime)s - %(levelname)s - %(message)s', 'datefmt': '%Y-%m-%d %H:%M:%S'},
        'pwd_audit': {
            'format': '%(asctime)s - %(levelname)s - %(operate_type)s - 用户%(operate_user)s - 主机%(host_ip)s - %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    # 日志器配置
    'loggers': {
        # Django默认日志器
        'django': {'handlers': ['console'], 'level': 'INFO', 'propagate': True},
        # 改密任务日志器
        'host_pwd_task': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        # 密码审计日志器（改密+查看）
        'host_pwd_audit': {'handlers': ['console', 'pwd_audit_file'], 'level': 'INFO', 'propagate': False},
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'




# ------------------- Celery 核心配置 -------------------
# 1. 消息中间件Broker：连接WSL2的Redis（带密码）
CELERY_BROKER_URL = f"redis://:{os.environ['REDIS_PASSWORD']}@172.17.200.47:6379/0"
# 2. 任务结果存储Backend：优先用django-db（Django Admin可看结果，无需改Redis）
CELERY_RESULT_BACKEND = 'django-db'


# 时区：和Django保持一致（比如Asia/Shanghai）
CELERY_TIMEZONE = 'Asia/Shanghai'
# 启用UTC（可选，建议开启）
CELERY_ENABLE_UTC = True

# ------------------- 扩展：将任务结果存到Django数据库（可选，推荐） -------------------
# 如果你想在Django Admin中查看任务结果，用这个替代上面的CELERY_RESULT_BACKEND
# INSTALLED_APPS中先添加'django_celery_results'
CELERY_RESULT_BACKEND = 'django-db'
# 任务结果过期时间（比如1天，单位秒）
CELERY_RESULT_EXPIRES = 86400

# ------------------- 扩展：定时任务配置（django-celery-beat） -------------------
# INSTALLED_APPS中添加'django_celery_beat'
# 定时任务存到Django数据库，支持Admin可视化配置
# 配置celery beat，每天 00:00 按城市和机房维度统计主机数量，并把统计数据写入数据库
CELERY_BEAT_SCHEDULE = {
    "daily_host_count_statistic": {
        "task": "statistic.tasks.batch_statistic_host_count",  # 批量统计的任务路径
        "schedule": crontab(hour=0, minute=0),  # 每天凌晨0点执行
        "args": (),
    },
    # 每8小时整点执行批量改密（0/8/16点，推荐）
    "batch_update_all_host_pwd": {
        "task": "host.tasks.batch_update_all_host_pwd",
        "schedule": crontab(hour="*/8", minute=0),
    },
}




