# Generated by Django 4.2 on 2026-02-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '城市管理',
            },
        ),
    ]
