# Generated by Django 4.2 on 2026-02-05 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server_room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField()),
                ('os_type', models.CharField(choices=[('Linux', 'Linux'), ('Windows', 'Windows')], default='Linux', max_length=10)),
                ('encrypted_pwd', models.CharField(blank=True, max_length=256, null=True, verbose_name='加密主机密码')),
                ('is_reachable', models.BooleanField(default=True)),
                ('last_ping_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('server_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_room.serverroom')),
            ],
            options={
                'verbose_name': '主机',
            },
        ),
    ]
